
project_id = "llndccqumkrblpgystom"

[api]
enabled = true
port = 54321
schemas = ["public", "storage"]

[functions]
[functions.restaurant-ai-analysis]
verify_jwt = true

[functions.generate-report]
verify_jwt = true
